# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Specify the operating system as WMF 5 (Windows Management Framework 5)
os: WMF 5

# Skip builds triggered by updates to the readme file
skip_commits:
  message: /updated readme.*/

install:
  # Install Pester using Chocolatey
  - choco install pester -y

build: off

test_script:
  # Execute the Pester tests using the script file
  #- ps: Invoke-Pester -Path '.\Tests' -EnableExit
  - ps: Invoke-Pester -Path '.\Shortcuts\Tests' -EnableExit

