version: 1.0.{build}

image: Visual Studio 2019

environment:
  PSModulePath: "$env:PSModulePath;$(Build.Repository.LocalPath)/src"

install:
  - ps: Install-Module -Name Pester -Force -SkipPublisherCheck

build_script:
  - ps: |
      $testResults = Invoke-Pester -Path './tests' -PassThru
      if ($testResults.FailedCount -gt 0) {
        $testResults | Format-Table -AutoSize
        throw "Pester tests failed!"
      }

test_script: {}

artifacts: []

branches:
  only:
    - master
